In [4]:
import os
from main_process import process_entitys, main

In [12]:
name_folder = 'dataset'
filenames = [n for n in os.listdir(name_folder) if n[0] != '.' and n[-1] == '1']

In [6]:
# for filename in filenames:
#     path_file_origin = os.path.join(name_folder, filename)
#     path_file_target = os.path.join(name_folder, f'{filename}.1')
#     main(path_file_origin, path_file_target)
# # end

In [7]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

(…)f3d3c277d6e90027e55de9125/.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

(…)7d6e90027e55de9125/1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(…)e2f80f3d3c277d6e90027e55de9125/README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

(…)f80f3d3c277d6e90027e55de9125/config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

(…)de9125/config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

(…)d3c277d6e90027e55de9125/data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

(…)90027e55de9125/sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

(…)6e90027e55de9125/special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

(…)f3d3c277d6e90027e55de9125/tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

(…)7d6e90027e55de9125/tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

(…)3d3c277d6e90027e55de9125/train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

(…)e2f80f3d3c277d6e90027e55de9125/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

(…)80f3d3c277d6e90027e55de9125/modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [44]:
from scipy import spatial
import numpy as np

def details_cosine_distance(e1, e2):
    return spatial.distance.cosine(e1, e2)
# end

In [36]:
def print_nxn(model, sentences):
    sims = np.zeros((len(sentences), len(sentences)))
    
    embeddings = model.encode(sentences)

    for i1, s1 in enumerate(embeddings):
        for i2, s2 in enumerate(embeddings):
            # if i2<= i1:
            #     continue
            # # end
            
            sims[i1][i2] = details_cosine_distance(s1, s2)
            # print('[{}]x[{}]: {}'.format(i1, i2, details_cosine_distance(s1, s2)))
        # end
    # end
    
    return sims
# end

In [45]:
sentences = []

for filename in filenames:
    path_file = os.path.join(name_folder, filename)
    with open(path_file, 'r') as file:
        lines = file.read().splitlines()
        sentence = ' '.join(lines)
        sentences.append((filename, sentence, len(sentence.split(' '))))
    # end
# end


sentences.append(('jinyuj_added1','profile restore op main vc task validator number',1))
sentences.append(('jinyuj_added2','virtual machine re configure com vmware vc runtime fault summary',1))


In [46]:
sims = print_nxn(model, [s[1] for s in sentences])

In [47]:
print(sims)

[[0.         0.38519031 0.4646095  0.28105122 0.49873126 0.64298287]
 [0.38519031 0.         0.18395644 0.20471239 0.31718999 0.38301444]
 [0.4646095  0.18395644 0.         0.37048256 0.1928001  0.21185768]
 [0.28105122 0.20471239 0.37048256 0.         0.48025465 0.55855316]
 [0.49873126 0.31718999 0.1928001  0.48025465 0.         0.64309645]
 [0.64298287 0.38301444 0.21185768 0.55855316 0.64309645 0.        ]]


In [48]:
sentences

[('3053311_error_log.txt.1',
  'host failback op vm connected validator number vms are connected host failback op vm powered on validator number vms are powered on apply profile op vm connected validator number vms are connected apply profile op vm powered on validator number vms are powered on apply profile op profile applied validator verified all profile requests have been applied successfully apply profile op main vc task validator number virtual machine re configure com vmware vc runtime fault summary com vmware vc invalid state the operation is not allowed in the current state apply profile op vm connected validator number vms are connected apply profile op vm powered on validator number vms are powered on apply profile op data health validator number checks passed for data health vsan master backup failure op vm connected validator number vms are connected vsan master backup failure op vm powered on validator number vms are powered on vsan master backup failure op data health va